GET http://localhost:4000/users

###
GET http://localhost:4000/me

# Mendapatkan user berdasarkan id
###
GET http://localhost:4000/users/7

# Mengupdate data user
###
PATCH http://localhost:4000/users/5
Content-Type: application/json

{
    "name": "Adelpiaa",
    "username": "delepipi",
    "email": "delepipi@gmail.com",
    "password": "123123",
    "confPassword": "123123"
}

# Menghapus user
###
DELETE http://localhost:4000/users/6

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "alip",
    "username": "pipi",
    "email": "pipi@gmail.com",
    "password": "123322",
    "confPassword": "123322"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "delepipi@gmail.com",
    "password": "123123"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout


# TRANSAKSI

###
GET http://localhost:4000/transaksi

###
GET http://localhost:4000/transaksitable

###
GET http://localhost:4000/transaksi/1

###
POST http://localhost:4000/transaksi
Content-Type: application/json

{
    "id_user": 5,
    "id_item": 1,
    "noHp": "082222222232",
    "quantity": 2,
    "address": "Kayutangi"
}

###
PATCH http://localhost:4000/transaksi/1
Content-Type: application/json

{
    "id_user": 5,
    "id_item": 1,
    "noHp": "082222222222",
    "quantity": 3,
    "address": "Kayutangi"
}

###
DELETE http://localhost:4000/transaksi/1

# Update saldo
###
POST http://localhost:4000/transaksi/5


# Search User
###
GET http://localhost:4000/users/search?search=iipp

# Search Transaksi
###
GET http://localhost:4000/transaksi/search?search=del

# Search Item
###
GET http://localhost:4000/items/search?search=buku






