GET http://localhost:4000/users

# Mendapatkan user berdasarkan id
###
GET http://localhost:4000/users/3

# Mengupdate data user
###
PATCH http://localhost:4000/users/3
Content-Type: application/json

{
    "name": "adel",
    "username": "pipi",
    "email": "pipi@gmail.com",
    "role": "user",
    "password": "123322",
    "confPassword": "123322"
}

# Menghapus user
###
DELETE http://localhost:4000/users/2

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "M Gymnastiar",
    "username": "Agim",
    "email": "agim@gmail.com",
    "password": "123322",
    "confPassword": "123322"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "agim@gmail.com",
    "password": "123322"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout


# TRANSAKSI

###
GET http://localhost:4000/transaksi

###
GET http://localhost:4000/transaksitable

###
GET http://localhost:4000/transaksi/1

###
POST http://localhost:4000/transaksi
Content-Type: application/json

{
    "id_user": 3,
    "id_item": 1,
    "noHp": "082222222232",
    "quantity": 2,
    "address": "Kayutangi"
}

###
PATCH http://localhost:4000/transaksi/1
Content-Type: application/json

{
    "id_user": 5,
    "id_item": 1,
    "noHp": "082222222222",
    "quantity": 3,
    "address": "Kayutangi"
}

###
DELETE http://localhost:4000/transaksi/1

# Update saldo
###
PATCH  http://localhost:4000/transaksi/balance/2

# Search User
###
GET http://localhost:4000/users?search=delphia

# Search Transaksi
###
GET http://localhost:4000/transaksitable?search=kaleng

# Search Item
###
GET http://localhost:4000/items?search=kaleng






